#!/bin/bash
distro = $( grep '^NAME' /etc/os-release | cut -d = -f 2 | tr -d '"' )

if [[ $distro == "Ubuntu"]];then
    echo "Ubuntu detected"


    echo "Installing zsh"
    sudo apt-get install zsh
    
    echo "Installing oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    

    echo "installing node version manager (nvm)"
    wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash

    echo "installing neovim"
    sudo apt-get install software-properties-common
    sudo apt install python3-neovim
    sudo add-apt-repository ppa:neovim-ppa/stable
    sudo apt-get update
    sudo apt-get install neovim
    
    # create folder structure
    echo "Creating folder structure"
    mkdir -p ~/programming
fi

echo "Done!"
